version: "3.9"

services:
  web:
    build: .
    command: gunicorn jobli.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: jobli_db
      POSTGRES_USER: jobli_user
      POSTGRES_PASSWORD: theone001
      
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
